scale: 0
chunksPerRun: 4
runPerTicks: 5
fastTicks: 20
canSeeOthers: true
showDistantWaypoints: false
mysql:
  enabled: false
  host: localhost
  port: 3306
  user: user
  pass: password
  database: database