name: ServerMinimap
main: de.craftlancer.serverminimap.ServerMinimap
version: 0.6.0
author: SydMontague
description: A serverside Minimap via maps.
permissions:
    minimap.fastupdate:
        description: Updates the minimap of the player much faster
        default: false
commands:
    waypoint:
        usage: /waypoint help
    minimap:
        usage: /minimap
        description: Gives you a minimap item
permissions:
    minimap.fastupdate:
        default: false
    minimap.command.waypoint.help:
        default: false
    minimap.command.waypoint.list:
        default: false
    minimap.command.waypoint.add:
        default: false
    minimap.command.waypoint.remove:
        default: false
    minimap.command.waypoint.hide:
        default: false
    minimap.command.minimap:
        default: op